"use strict";(()=>{var e={};e.id=443,e.ids=[443],e.modules={399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},3977:e=>{e.exports=require("node:fs/promises")},9411:e=>{e.exports=require("node:path")},6179:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>g,patchFetch:()=>v,requestAsyncStorage:()=>l,routeModule:()=>u,serverHooks:()=>c,staticGenerationAsyncStorage:()=>f});var a={};r.r(a),r.d(a,{POST:()=>p});var n=r(9303),i=r(8716),o=r(3131),d=r(7070),s=r(4589);async function p(e,{params:t}){let r=await e.formData().catch(()=>null),a=r?.get("returnTo")??"/admin/mail-queue",n=r?.get("approvedBy")??"Admin reviewer";try{let r=await (0,s.TU)(t.id,n),i=new URL(a,e.url);return i.searchParams.set("mailing",r.alreadyApproved?"already-approved":"approved"),d.NextResponse.redirect(i,303)}catch(e){return d.NextResponse.json({error:e instanceof Error?e.message:"Approval failed."},{status:400})}}let u=new n.AppRouteRouteModule({definition:{kind:i.x.APP_ROUTE,page:"/api/disputes/[id]/approve/route",pathname:"/api/disputes/[id]/approve",filename:"route",bundlePath:"app/api/disputes/[id]/approve/route"},resolvedPagePath:"C:\\Users\\kj\\credit-repair-mvp\\next-credit-foundation\\app\\api\\disputes\\[id]\\approve\\route.ts",nextConfigOutput:"",userland:a}),{requestAsyncStorage:l,staticGenerationAsyncStorage:f,serverHooks:c}=u,g="/api/disputes/[id]/approve/route";function v(){return(0,o.patchFetch)({serverHooks:c,staticGenerationAsyncStorage:f})}},4589:(e,t,r)=>{r.d(t,{TU:()=>v,iK:()=>m,sB:()=>g});var a=r(6228),n=r(7836),i=r(5826),o=r(2790);function d(e){return[e.name,e.street1,e.street2,`${e.city}, ${e.state} ${e.postalCode}`].filter(Boolean).join("\n")}function s(e,t,r){let a=r?i.es[r]:null;return["Credu Consulting - Final Mailing Version",`Client: ${t.fullName}`,`Sender:
${d(o.j)}`,a?`Recipient:
${d({name:a.recipientName,street1:a.street1,street2:a.street2,city:a.city,state:a.state,postalCode:a.postalCode})}`:null,`Version: ${e.versionNumber}`,`Generated: ${e.createdAt}`,"",...e.letterText.split("\n")].filter(Boolean).join("\n")}function p(e){let t=e.replaceAll("\\","\\\\").replaceAll("(","\\(").replaceAll(")","\\)"),r=`BT /F1 11 Tf 50 760 Td (${t.replaceAll("\n",") Tj T* (")}) Tj ET`,a=["1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj","2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj","3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >> endobj",`4 0 obj << /Length ${r.length} >> stream
${r}
endstream endobj`,"5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj"],n="%PDF-1.4\n",i=[];for(let e of a)i.push(n.length),n+=`${e}
`;let o=n.length;for(let e of(n+=`xref
0 ${a.length+1}
0000000000 65535 f 
`,i))n+=`${e.toString().padStart(10,"0")} 00000 n 
`;return n+=`trailer << /Size ${a.length+1} /Root 1 0 R >>
startxref
${o}
%%EOF`,Buffer.from(n,"utf8")}var u=r(9338),l=r(4805),f=r(5154);function c(){return new Date().toISOString()}async function g(e){return(0,f.t0)(e)}async function v(e,t="Admin reviewer"){let{dispute:r,currentVersion:a}=await (0,f.Zc)(e);if(!r||!a)throw Error("Dispute record not found.");if("awaiting_admin_approval"!==r.workflowStatus)return{dispute:r,version:a,alreadyApproved:!0};let i=c(),o={...a,id:`${r.id}_v${a.versionNumber+1}`,versionNumber:a.versionNumber+1,kind:"admin_approved",generatedBy:"admin",approvedAt:i,createdAt:i,notes:[...a.notes,"Approved for mailing after admin review."]},d={...r,currentVersionId:o.id,workflowStatus:(0,u.$8)({family:"mailing",fromStatus:"awaiting_admin_approval",toStatus:"approved_pending_pdf",context:{hasDisputeDraft:!0,adminApproved:!0}}).nextStatus,approvedAt:i,approvedBy:t,updatedAt:i};return await (0,f.Pc)(o),await (0,f.c0)(d),await (0,f.B7)({id:`event_${r.id}_approved_${i}`,disputeId:e,eventType:"approved",occurredAt:i,actor:t,notes:"Dispute approved for mailing."}),await (0,l.$)({type:n.aR.disputeApproved,aggregateType:"dispute",aggregateId:e,actorType:"admin",actorId:t,payload:{leadId:r.leadId,bureau:r.bureau,versionId:o.id,workflowStatus:d.workflowStatus},metadata:{source:"approveDisputeForMailing"}}),{dispute:d,version:o,alreadyApproved:!1}}async function m(e){let{dispute:t,currentVersion:r}=await (0,f.Zc)(e);if(!t||!r)throw Error("Dispute record not found.");if("approved_pending_pdf"!==t.workflowStatus&&"awaiting_payment"!==t.workflowStatus&&"paid_ready_to_send"!==t.workflowStatus)throw Error("Dispute is not ready for final mailing PDF generation.");let i=(0,a.zs)(t.leadId);if(!i)throw Error("Lead not found.");if("mailing_final"===r.kind&&r.pdfGeneratedAt){let e=p(s(r,i));return{dispute:t,version:r,pdfBuffer:e}}let o=c(),d={...r,id:`${t.id}_v${r.versionNumber+1}`,versionNumber:r.versionNumber+1,kind:"mailing_final",generatedBy:"system",createdAt:o,pdfGeneratedAt:o,pdfAssetPath:`/generated/${t.id}-mailing-final.pdf`,notes:[...r.notes,"Mailing-ready PDF version generated."]},g="approved_pending_pdf"===t.workflowStatus?(0,u.$8)({family:"mailing",fromStatus:"approved_pending_pdf",toStatus:"awaiting_payment",context:{hasFinalPdf:!0}}).nextStatus:t.workflowStatus,v={...t,currentVersionId:d.id,workflowStatus:g,updatedAt:o};await (0,f.Pc)(d),await (0,f.c0)(v),await (0,f.B7)({id:`event_${t.id}_pdf_${o}`,disputeId:e,eventType:"pdf_generated",occurredAt:o,actor:"system",notes:"Mailing-ready PDF version generated."}),await (0,l.$)({type:n.aR.disputeFinalPdfGenerated,aggregateType:"dispute",aggregateId:e,actorType:"system",actorId:"pdf_generator",payload:{leadId:t.leadId,bureau:t.bureau,versionId:d.id,pdfAssetPath:d.pdfAssetPath,workflowStatus:v.workflowStatus},metadata:{source:"generateFinalMailingVersion"}});let m=p(s(d,i,t.bureau));return{dispute:v,version:d,pdfBuffer:m}}}};var t=require("../../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),a=t.X(0,[276,972,228,754],()=>r(6179));module.exports=a})();