import type {
  DefectCategory,
  DefectCode,
  DefectOutputTemplateKey,
  DefectSeverity,
  DefectStrategyLevel,
  DefectTone,
} from "@/lib/types";

export type DefectCodeDefinition = {
  code: DefectCode;
  title: string;
  category: DefectCategory;
  severity: DefectSeverity;
  laws: string[];
  description: string;
  consumerHarm: string;
  disputeGoal: string;
  suggestedTone: DefectTone;
  strategyLevel: DefectStrategyLevel;
  outputTemplateKey: DefectOutputTemplateKey;
  escalationReady: boolean;
};

export const defectCodeRegistry: Record<DefectCode, DefectCodeDefinition> = {
  inconsistent_balance: {
    code: "inconsistent_balance",
    title: "Inconsistent balance",
    category: "balance",
    severity: "high",
    laws: ["FCRA § 1681e(b)"],
    description: "The same account balance conflicts across bureaus or within the same reporting block.",
    consumerHarm: "Inflates perceived debt load and can suppress scores or lending decisions.",
    disputeGoal: "Force reinvestigation and correction of the reported balance.",
    suggestedTone: "firm",
    strategyLevel: "medium",
    outputTemplateKey: "balance_inconsistency",
    escalationReady: true,
  },
  inconsistent_payment_history: {
    code: "inconsistent_payment_history",
    title: "Inconsistent payment history",
    category: "payment_history",
    severity: "high",
    laws: ["FCRA § 1681e(b)"],
    description: "Payment history indicators conflict with each other or with the reported account status.",
    consumerHarm: "Creates false delinquency signals and damages score trajectory.",
    disputeGoal: "Challenge the accuracy of payment-history reporting and demand verified history.",
    suggestedTone: "firm",
    strategyLevel: "medium",
    outputTemplateKey: "payment_history_inconsistency",
    escalationReady: true,
  },
  inconsistent_status: {
    code: "inconsistent_status",
    title: "Inconsistent status",
    category: "status",
    severity: "medium",
    laws: ["FCRA § 1681e(b)"],
    description: "Status labels conflict across bureaus or with other account fields.",
    consumerHarm: "Misstates account standing and can change underwriting outcomes.",
    disputeGoal: "Require the bureau to correct or remove the inconsistent status reporting.",
    suggestedTone: "firm",
    strategyLevel: "medium",
    outputTemplateKey: "status_inconsistency",
    escalationReady: true,
  },
  dispute_not_marked: {
    code: "dispute_not_marked",
    title: "Dispute not marked",
    category: "dispute_reporting",
    severity: "high",
    laws: ["FCRA § 1681s-2(a)(3)"],
    description: "The account appears disputed but one or more bureaus fail to show that notation.",
    consumerHarm: "Prevents lenders from seeing that the item is under active dispute.",
    disputeGoal: "Compel the bureau or furnisher to add the required dispute notation.",
    suggestedTone: "aggressive",
    strategyLevel: "high",
    outputTemplateKey: "dispute_notation_missing",
    escalationReady: true,
  },
  obsolete_debt: {
    code: "obsolete_debt",
    title: "Obsolete debt",
    category: "obsolescence",
    severity: "critical",
    laws: ["FCRA § 1681c(a)"],
    description: "A derogatory account appears to remain beyond the standard seven-year reporting period.",
    consumerHarm: "Keeps expired negative data active and damages long-term recovery.",
    disputeGoal: "Demand immediate deletion of obsolete reporting.",
    suggestedTone: "legal_leverage",
    strategyLevel: "high",
    outputTemplateKey: "obsolete_debt",
    escalationReady: true,
  },
  suspected_re_aging: {
    code: "suspected_re_aging",
    title: "Suspected re-aging",
    category: "re_aging",
    severity: "critical",
    laws: ["FCRA § 1681s-2(a)(1)", "FCRA § 1681e(b)"],
    description: "Dates or derogatory timing suggest the delinquency window may have been improperly refreshed.",
    consumerHarm: "Extends harmful reporting life and misstates the true age of the debt.",
    disputeGoal: "Force validation of delinquency timing and correct any improper re-aging.",
    suggestedTone: "legal_leverage",
    strategyLevel: "high",
    outputTemplateKey: "re_aging",
    escalationReady: true,
  },
  duplicate_tradeline: {
    code: "duplicate_tradeline",
    title: "Duplicate tradeline",
    category: "duplication",
    severity: "high",
    laws: ["FCRA § 1681e(b)"],
    description: "The same tradeline appears more than once or overlaps in a way that suggests double-reporting.",
    consumerHarm: "Artificially increases debt exposure and derogatory impact.",
    disputeGoal: "Collapse duplicate reporting into the single accurate tradeline.",
    suggestedTone: "firm",
    strategyLevel: "medium",
    outputTemplateKey: "duplicate_reporting",
    escalationReady: true,
  },
  amount_misrepresented: {
    code: "amount_misrepresented",
    title: "Amount misrepresented",
    category: "amount",
    severity: "high",
    laws: ["FCRA § 1681e(b)"],
    description: "The reported balance, past-due amount, or total amount conflicts with the account condition.",
    consumerHarm: "Makes the obligation appear larger or more delinquent than supported.",
    disputeGoal: "Correct the reported amount fields or delete unverifiable figures.",
    suggestedTone: "firm",
    strategyLevel: "medium",
    outputTemplateKey: "amount_misrepresented",
    escalationReady: true,
  },
  status_misrepresented: {
    code: "status_misrepresented",
    title: "Status misrepresented",
    category: "status",
    severity: "high",
    laws: ["FCRA § 1681e(b)"],
    description: "The account status is represented in a way that conflicts with balances, payment state, or remarks.",
    consumerHarm: "Mischaracterizes account health and can intensify score suppression.",
    disputeGoal: "Require accurate status coding or deletion of unverifiable status data.",
    suggestedTone: "firm",
    strategyLevel: "medium",
    outputTemplateKey: "status_inconsistency",
    escalationReady: true,
  },
  unexplained_fee_increase: {
    code: "unexplained_fee_increase",
    title: "Unexplained fee increase",
    category: "fees",
    severity: "medium",
    laws: ["FCRA § 1681e(b)"],
    description: "The account balance reflects fees or jumps that are not explained by the available reporting data.",
    consumerHarm: "Raises the debt burden without a clear reporting basis.",
    disputeGoal: "Challenge unexplained balance growth and require a validated breakdown.",
    suggestedTone: "factual",
    strategyLevel: "low",
    outputTemplateKey: "fee_increase",
    escalationReady: false,
  },
  unverifiable_account_data: {
    code: "unverifiable_account_data",
    title: "Unverifiable account data",
    category: "verification",
    severity: "medium",
    laws: ["FCRA § 1681i(a)", "FCRA § 1681e(b)"],
    description: "Core account data is incomplete, contradictory, or insufficient to verify the tradeline.",
    consumerHarm: "Leaves the client with harmful reporting that may not be fully supportable.",
    disputeGoal: "Require reinvestigation or deletion of unverifiable fields.",
    suggestedTone: "factual",
    strategyLevel: "low",
    outputTemplateKey: "unverifiable_data",
    escalationReady: false,
  },
  transfer_sale_double_reporting: {
    code: "transfer_sale_double_reporting",
    title: "Transfer or sale double-reporting",
    category: "duplication",
    severity: "high",
    laws: ["FCRA § 1681e(b)"],
    description: "A transferred or sold debt appears to be reported in overlapping form by multiple entities.",
    consumerHarm: "Duplicates derogatory impact and overstates collection exposure.",
    disputeGoal: "Force accurate reporting of the original and transferred account relationship.",
    suggestedTone: "aggressive",
    strategyLevel: "high",
    outputTemplateKey: "duplicate_reporting",
    escalationReady: true,
  },
  mixed_file_issue: {
    code: "mixed_file_issue",
    title: "Mixed file issue",
    category: "mixed_file",
    severity: "critical",
    laws: ["FCRA § 1681e(b)", "FCRA § 1681i(a)"],
    description: "Tradeline characteristics suggest identity-mixing or another consumer’s data in the file.",
    consumerHarm: "Creates severe identity and credit injury beyond a normal account dispute.",
    disputeGoal: "Separate the consumer file and remove misattributed tradelines immediately.",
    suggestedTone: "legal_leverage",
    strategyLevel: "high",
    outputTemplateKey: "mixed_file",
    escalationReady: true,
  },
  inconsistent_delinquency_activity_dates: {
    code: "inconsistent_delinquency_activity_dates",
    title: "Inconsistent delinquency or activity dates",
    category: "date_integrity",
    severity: "high",
    laws: ["FCRA § 1681e(b)", "FCRA § 1681c(c)"],
    description: "The timeline of activity, delinquency, or reporting dates conflicts across the file.",
    consumerHarm: "Can distort obsolescence timing and exaggerate recency of derogatory activity.",
    disputeGoal: "Force the bureau to verify the correct timeline or delete inconsistent date reporting.",
    suggestedTone: "aggressive",
    strategyLevel: "high",
    outputTemplateKey: "date_inconsistency",
    escalationReady: true,
  },
};

export function getDefectCodeDefinition(code: DefectCode) {
  return defectCodeRegistry[code];
}

export function listDefectCodeDefinitions() {
  return Object.values(defectCodeRegistry);
}
