import type { DisputeVersionRecord } from "@/lib/types";

function getVersionTone(kind: DisputeVersionRecord["kind"]) {
  if (kind === "mailing_final") {
    return "border-emerald-400/20 bg-emerald-500/10 text-emerald-900";
  }
  if (kind === "admin_approved") {
    return "border-amber-400/20 bg-amber-500/10 text-amber-900";
  }
  return "border-black/10 bg-surface-light-soft text-zinc-800";
}

export function DisputeVersionHistoryPanel({
  versions,
}: {
  versions: DisputeVersionRecord[];
}) {
  if (!versions.length) {
    return null;
  }

  return (
    <section className="rounded-[1.6rem] border border-black/10 bg-white/72 p-5">
      <div className="space-y-3">
        <p className="eyebrow">Draft version history</p>
        <h3 className="font-display text-3xl uppercase leading-[0.92] tracking-[0.03em] text-text-dark">
          Every version in the review chain.
        </h3>
        <p className="text-sm leading-7 text-zinc-600">
          AI draft, approved edit, and final mailing versions stay visible so admin can review changes without losing the chain.
        </p>
      </div>

      <div className="mt-5 grid gap-3">
        {[...versions]
          .sort((a, b) => b.versionNumber - a.versionNumber)
          .map((version) => (
            <article
              key={version.id}
              className={`rounded-[1.2rem] border px-4 py-4 ${getVersionTone(version.kind)}`}
            >
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div className="space-y-1">
                  <p className="font-semibold uppercase tracking-[0.08em]">
                    Version {version.versionNumber}
                  </p>
                  <p className="text-sm leading-7">
                    {version.kind.replaceAll("_", " ")} | generated by {version.generatedBy}
                  </p>
                </div>
                <span className="text-[11px] uppercase tracking-[0.22em]">
                  {new Date(version.createdAt).toLocaleString()}
                </span>
              </div>

              <p className="mt-3 text-sm leading-7">{version.summary}</p>

              {version.notes.length ? (
                <div className="mt-3 rounded-[1rem] border border-black/10 bg-white/55 px-3 py-3 text-sm leading-7 text-zinc-700">
                  {version.notes.join(" ")}
                </div>
              ) : null}
            </article>
          ))}
      </div>
    </section>
  );
}
